vector-add: ability to change vector size (#452)
* vector-add execution time is increased

vector-add sample is updated to have longer execution time for correct illustration of Advisor GPU Roofline feature.

* vector-add-buffers.cpp compilation fix

static_cast<int>( ) is added to fix the compilation error on Linux:
src/vector-add-buffers.cpp:147:26: error: non-constant-expression cannot be narrowed from type 'unsigned long' to 'int' in initializer list [-Wc++11-narrowing]
  int indices[]{0, 1, 2, (a.size() - 1)};

* vector-add: new parameter vector size